-- Populate the 'characters' table
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಅ', 'a', 'vowel');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಆ', 'aa', 'vowel');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಇ', 'i', 'vowel');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಈ', 'ii', 'vowel');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಉ', 'u', 'vowel');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಊ', 'uu', 'vowel');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಋ', 'ru', 'vowel');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಎ', 'e', 'vowel');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಏ', 'ee', 'vowel');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಐ', 'ai', 'vowel');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಒ', 'o', 'vowel');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಓ', 'oo', 'vowel');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಔ', 'au', 'vowel');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಅಂ', 'am', 'vowel');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಅಃ', 'ah', 'vowel');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಕ', 'ka', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಖ', 'kha', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಗ', 'ga', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಘ', 'gha', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಙ', 'nga', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಚ', 'cha', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಛ', 'chha', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಜ', 'ja', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಝ', 'jha', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಞ', 'nya', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಟ', 'ṭa', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಠ', 'ṭha', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಡ', 'ḍa', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಢ', 'ḍha', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಣ', 'ṇa', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ತ', 'ta', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಥ', 'tha', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ದ', 'da', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಧ', 'dha', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ನ', 'na', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಪ', 'pa', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಫ', 'pha', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಬ', 'ba', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಭ', 'bha', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಮ', 'ma', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಯ', 'ya', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ರ', 'ra', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಲ', 'la', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ವ', 'va', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಶ', 'sha', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಷ', 'ṣa', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಸ', 'sa', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಹ', 'ha', 'consonant');
INSERT INTO characters (kannada_char, transliteration, type) VALUES ('ಳ', 'ḷa', 'consonant');

-- Populate the 'words' table
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಮನೆ', 'mane', 'house', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹಣ್ಣು', 'haṇṇu', 'fruit', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಪಥ', 'patha', 'path', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಅಮ್ಮ', 'amma', 'mother', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಅಪ್ಪ', 'appa', 'father', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಮರ', 'mara', 'tree', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಗಿಡ', 'giḍa', 'plant', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಊಟ', 'ūṭa', 'meal', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹಾಲು', 'hālu', 'milk', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನೀರು', 'nīru', 'water', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕಣ್ಣು', 'kaṇṇu', 'eye', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬಾಯಿ', 'bāyi', 'mouth', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನಾಯಿ', 'nāyi', 'dog', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬೆಕ್ಕು', 'bekku', 'cat', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಪುಸ್ತಕ', 'pustaka', 'book', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬರೆ', 'bare', 'write (imperative)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಓದು', 'ōdu', 'read (imperative)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕೆಂಪು', 'kempu', 'red', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹಸಿರು', 'hasiru', 'green', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ದಿನ', 'dina', 'day', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ರಾತ್ರಿ', 'rātri', 'night', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹೂವು', 'hūvu', 'flower', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕಲ್ಲು', 'kallu', 'stone', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಮಣ್ಣು', 'maṇṇu', 'soil / mud', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬಾನು', 'bānu', 'sky', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಗಾಳಿ', 'gāḷi', 'wind / air', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬೆಂಕಿ', 'benki', 'fire', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹೊಗೆ', 'hoge', 'smoke', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಅಕ್ಕ', 'akka', 'elder sister', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ತಂಗಿ', 'tangi', 'younger sister', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಅಣ್ಣ', 'aṇṇa', 'elder brother', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ತಮ್ಮ', 'tamma', 'younger brother', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಗೆಳೆಯ', 'geḷeya', 'friend (male)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಗೆಳತಿ', 'geḷati', 'friend (female)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನಾನು', 'nānu', 'I', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನೀನು', 'nīnu', 'you (singular/informal)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಅವನು', 'avanu', 'he', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಅವಳು', 'avaḷu', 'she', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಅದು', 'adu', 'it / that', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಇದು', 'idu', 'this', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹೌದು', 'houdu', 'yes', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಇಲ್ಲ', 'illa', 'no / not', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬಾ', 'bā', 'come (imperative, informal)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹೋಗು', 'hōgu', 'go (imperative)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ತಿನ್ನು', 'tinnu', 'eat (imperative)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕುಡಿ', 'kuḍi', 'drink (imperative)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನೋಡು', 'nōḍu', 'see / look / watch (imperative)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಮಾಡು', 'māḍu', 'do (imperative)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕೇಳು', 'kēḷu', 'listen / ask (imperative)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹೇಳು', 'hēḷu', 'tell / say (imperative)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನಗು', 'nagu', 'laugh (imperative)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಅಳು', 'aḷu', 'cry (imperative)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನಡೆ', 'naḍe', 'walk (imperative)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಓಡು', 'ōḍu', 'run (imperative)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕುಳಿತುಕೊ', 'kuḷituko', 'sit (imperative)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನಿಲ್ಲು', 'nillu', 'stand / stop (imperative)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕೊಡು', 'koḍu', 'give (imperative)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ತೆಗೆದುಕೊ', 'tegeduko', 'take (imperative)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಒಂದು', 'ondu', 'one', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಎರಡು', 'eraḍu', 'two', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಮೂರು', 'mūru', 'three', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನಾಲ್ಕು', 'nālku', 'four', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಐದು', 'aidu', 'five', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ದೊಡ್ಡ', 'doḍḍa', 'big / large', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಚಿಕ್ಕ', 'cikka', 'small / little', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹೊಸ', 'hosa', 'new', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹಳೆ', 'haḷe', 'old', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಒಳ್ಳೆ', 'oḷḷe', 'good', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕೆಟ್ಟ', 'keṭṭa', 'bad', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬಿಸಿ', 'bisi', 'hot', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ತಣ್ಣಗೆ', 'taṇṇage', 'cold', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬಿಳಿ', 'biḷi', 'white', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕಪ್ಪು', 'kappu', 'black', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನೀಲಿ', 'nīli', 'blue', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹಳದಿ', 'haḷadi', 'yellow', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬಣ್ಣ', 'baṇṇa', 'color', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹಣ', 'haṇa', 'money', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಅಂಗಡಿ', 'angaḍi', 'shop', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ದಾರ', 'dāra', 'thread', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬಟ್ಟೆ', 'baṭṭe', 'cloth / clothes', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕೈ', 'kai', 'hand', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕಾಲು', 'kālu', 'leg / foot', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ತಲೆ', 'tale', 'head', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹೊಟ್ಟೆ', 'hoṭṭe', 'stomach', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬೆನ್ನು', 'bennu', 'back', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕೂದಲು', 'kūdalu', 'hair', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಮೂಗು', 'mūgu', 'nose', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕಿವಿ', 'kivi', 'ear', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬೆರಳು', 'beraḷu', 'finger / toe', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನಗರ', 'nagara', 'city / town', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹಳ್ಳಿ', 'haḷḷi', 'village', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ರಸ್ತೆ', 'raste', 'road / street', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕಾರು', 'kāru', 'car', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬಸ್ಸು', 'bassu', 'bus', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ದಾರಿ', 'dāri', 'way / path', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬಾಗಿಲು', 'bāgilu', 'door', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕಿಟಕಿ', 'kiṭaki', 'window', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಮೇಜು', 'mēju', 'table', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕುರ್ಚಿ', 'kurci', 'chair', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹಾಸಿಗೆ', 'hāsige', 'bed / mattress', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಪೆನ್ನು', 'pennu', 'pen', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕಾಗದ', 'kāgada', 'paper', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಶಾಲೆ', 'śāle', 'school', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕೆಲಸ', 'kelasa', 'work / job', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಆಟ', 'āṭa', 'game / play', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹಾಡು', 'hāḍu', 'song / sing (imperative)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಮಾತು', 'mātu', 'talk / speech / word', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸಂತೆ', 'sante', 'market (weekly fair)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ತಾಯಿ', 'tāyi', 'mother (alt)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ತಂದೆ', 'tande', 'father (alt)', 1);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನದಿ', 'nadi', 'river', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬೆಟ್ಟ', 'beṭṭa', 'hill / mountain', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕಾಡು', 'kāḍu', 'forest', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸೂರ್ಯ', 'sūrya', 'sun', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಚಂದ್ರ', 'candra', 'moon', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನಕ್ಷತ್ರ', 'nakṣatra', 'star', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಮೋಡ', 'mōḍa', 'cloud', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಮಳೆ', 'maḷe', 'rain', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಗಂಟೆ', 'ganṭe', 'bell / hour', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸಮಯ', 'samaya', 'time', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಇಂದು', 'indu', 'today', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನಾಳೆ', 'nāḷe', 'tomorrow', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನಿನ್ನೆ', 'ninne', 'yesterday', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ವಾರ', 'vāra', 'week', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ತಿಂಗಳು', 'tingaḷu', 'month', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ವರ್ಷ', 'varṣa', 'year', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬೆಳಿಗ್ಗೆ', 'beḷigge', 'morning', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸಂಜೆ', 'sanje', 'evening', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ದೇವರು', 'dēvaru', 'god', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಗುಡಿ', 'guḍi', 'temple', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಪ್ರಶ್ನೆ', 'praśne', 'question', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಉತ್ತರ', 'uttara', 'answer / north', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಪ್ರೀತಿ', 'prīti', 'love', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ದ್ವೇಷ', 'dvēṣa', 'hatred', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕೋಪ', 'kōpa', 'anger', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಶಾಂತಿ', 'śānti', 'peace', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಧೈರ್ಯ', 'dhairya', 'courage', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಭಯ', 'bhaya', 'fear', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸುಂದರ', 'sundara', 'beautiful / handsome', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಮುಖ', 'mukha', 'face', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ದೇಹ', 'dēha', 'body', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಆರೋಗ್ಯ', 'ārōgya', 'health', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಶಕ್ತಿ', 'śakti', 'strength / power', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಜ್ಞಾನ', 'jñāna', 'knowledge', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಭಾಷೆ', 'bhāṣe', 'language', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ದೇಶ', 'dēśa', 'country', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ರಾಜ್ಯ', 'rājya', 'state / kingdom', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಜನ', 'jana', 'people', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಗಂಡ', 'gaṇḍa', 'husband', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹೆಂಡತಿ', 'henḍati', 'wife', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಮಗು', 'magu', 'child / baby', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹುಡುಗ', 'huḍuga', 'boy', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹುಡುಗಿ', 'huḍugi', 'girl', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸ್ನೇಹಿತ', 'snēhita', 'friend (male, formal)', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸ್ನೇಹಿತೆ', 'snēhite', 'friend (female, formal)', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಶಿಕ್ಷಕ', 'śikṣaka', 'teacher (male)', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಶಿಕ್ಷಕಿ', 'śikṣaki', 'teacher (female)', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ವಿದ್ಯಾರ್ಥಿ', 'vidyārthi', 'student', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ವೈದ್ಯ', 'vaidya', 'doctor', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಆಹಾರ', 'āhāra', 'food', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ತರಕಾರಿ', 'tarakāri', 'vegetable', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಅಕ್ಕಿ', 'akki', 'rice (uncooked)', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಅನ್ನ', 'anna', 'rice (cooked)', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ರುಚಿ', 'ruci', 'taste', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸಿಹಿ', 'sihi', 'sweet', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹುಳಿ', 'huḷi', 'sour', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಖಾರ', 'khāra', 'spicy / hot', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಉಪ್ಪು', 'uppu', 'salt', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕಹಿ', 'kahi', 'bitter', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹಸಿವು', 'hasivu', 'hunger', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬಾಯಾರಿಕೆ', 'bāyārike', 'thirst', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನಿದ್ರೆ', 'nidre', 'sleep', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬೇಗ', 'bēga', 'quickly / soon', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನಿಧಾನ', 'nidhāna', 'slowly', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಇಲ್ಲಿ', 'illi', 'here', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಅಲ್ಲಿ', 'alli', 'there', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಎಲ್ಲಿ', 'elli', 'where', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹೇಗೆ', 'hēge', 'how', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಯಾಕೆ', 'yāke', 'why', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಯಾರು', 'yāru', 'who', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಏನು', 'ēnu', 'what', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಯಾವಾಗ', 'yāvāga', 'when', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಎಷ್ಟು', 'eṣṭu', 'how much / how many', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ದೊಡ್ಡದು', 'doḍḍadu', 'big one', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಚಿಕ್ಕದು', 'cikkadu', 'small one', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹತ್ತಿರ', 'hattira', 'near', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ದೂರ', 'dūra', 'far', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಮೇಲೆ', 'mēle', 'on / above / up', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕೆಳಗೆ', 'keḷage', 'under / below / down', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಒಳಗೆ', 'oḷage', 'inside', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹೊರಗೆ', 'horage', 'outside', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಮುಂದೆ', 'munde', 'in front / ahead', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹಿಂದೆ', 'hinde', 'behind / back', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಪಕ್ಕ', 'pakka', 'beside / next to', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಮಧ್ಯ', 'madhya', 'middle / center', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸುತ್ತ', 'sutta', 'around', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನೇರ', 'nēra', 'straight', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬಲ', 'bala', 'right (direction)', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಎಡ', 'eḍa', 'left (direction)', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ತುಂಬಾ', 'tumbā', 'very / much / full', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸ್ವಲ್ಪ', 'svalpa', 'a little / few', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹೆಚ್ಚು', 'heccu', 'more', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕಡಿಮೆ', 'kaḍime', 'less / low', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸುಲಭ', 'sulabha', 'easy', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕಷ್ಟ', 'kaṣṭa', 'difficult / hard', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಶುದ್ಧ', 'śuddha', 'pure / clean', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಪ್ರಾಣಿ', 'prāṇi', 'animal', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಪಕ್ಷಿ', 'pakṣi', 'bird', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಮೀನು', 'mīnu', 'fish', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹಾವು', 'hāvu', 'snake', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಆನೆ', 'āne', 'elephant', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕುದುರೆ', 'kudure', 'horse', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹಸು', 'hasu', 'cow', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಇರುವೆ', 'iruve', 'ant', 2);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ವಿಮಾನ', 'vimāna', 'airplane', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ರೈಲು', 'railu', 'train', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹಡಗು', 'haḍagu', 'ship', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸಮುದ್ರ', 'samudra', 'sea / ocean', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಪ್ರಯಾಣ', 'prayāṇa', 'journey / travel', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಗ್ರಾಮ', 'grāma', 'village (formal)', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನಕ್ಷೆ', 'nakṣe', 'map', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸರ್ಕಾರ', 'sarkāra', 'government', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕಾನೂನು', 'kānūnu', 'law', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನ್ಯಾಯ', 'nyāya', 'justice', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಅಪರಾಧ', 'aparādha', 'crime', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಶಿಕ್ಷೆ', 'śikṣe', 'punishment', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸ್ವಾತಂತ್ರ್ಯ', 'svātantrya', 'freedom / independence', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹೋರಾಟ', 'hōrāṭa', 'struggle / fight', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸಮಾಜ', 'samāja', 'society', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸಂಸ್ಕೃತಿ', 'saṁskṛti', 'culture', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಪರಂಪರೆ', 'parampare', 'tradition / heritage', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಧರ್ಮ', 'dharma', 'religion / duty', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನಂಬಿಕೆ', 'nambike', 'belief / trust', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ವಿಜ್ಞಾನ', 'vijñāna', 'science', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ತಂತ್ರಜ್ಞಾನ', 'tantrajñāna', 'technology', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಪರಿಸರ', 'parisara', 'environment', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಭವಿಷ್ಯ', 'bhaviṣya', 'future', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಭೂತಕಾಲ', 'bhūtakāla', 'past tense', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ವರ್ತಮಾನ', 'vartamāna', 'present', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕಲೆ', 'kale', 'art', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸಂಗೀತ', 'sangīta', 'music', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನೃತ್ಯ', 'nṛtya', 'dance', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನಾಟಕ', 'nāṭaka', 'drama / play', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಚಿತ್ರ', 'citra', 'picture / painting / movie', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸಾಹಿತ್ಯ', 'sāhitya', 'literature', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕವಿತೆ', 'kavite', 'poem', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕಥೆ', 'kathe', 'story', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಲೇಖನ', 'lēkhana', 'article / writing', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ವ್ಯಾಪಾರ', 'vyāpāra', 'business / trade', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಉದ್ಯೋಗ', 'udyōga', 'employment / job', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕೃಷಿ', 'kṛṣi', 'agriculture', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ರೈತ', 'raita', 'farmer', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಭೂಮಿ', 'bhūmi', 'earth / land', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬೆಳೆ', 'beḷe', 'crop', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನೀರುಹಾಕು', 'nīruhāku', 'to water (plants)', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಅಡುಗೆ', 'aḍuge', 'cooking / kitchen', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಪಾತ್ರೆ', 'pātre', 'vessel / container', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಚಮಚ', 'camaca', 'spoon', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ತಟ್ಟೆ', 'taṭṭe', 'plate', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಲೋಟ', 'lōṭa', 'glass / tumbler', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸ್ನೇಹ', 'snēha', 'friendship', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸಂಬಂಧ', 'sambandha', 'relationship', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕುಟುಂಬ', 'kuṭumba', 'family', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನೆರೆಹೊರೆ', 'nerehore', 'neighborhood', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸಹಾಯ', 'sahāya', 'help / assistance', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಉಡುಗೊರೆ', 'uḍugore', 'gift / present', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಹಬ್ಬ', 'habba', 'festival', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಆಚರಣೆ', 'ācaraṇe', 'celebration / practice', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕಾರ್ಯಕ್ರಮ', 'kāryakrama', 'program / event', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಆಹ್ವಾನ', 'āhvāna', 'invitation', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಪ್ರಾರ್ಥನೆ', 'prārthane', 'prayer', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಆಶೀರ್ವಾದ', 'āśīrvāda', 'blessing', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸಂತೋಷ', 'santōṣa', 'happiness / joy', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ದುಃಖ', 'duḥkha', 'sadness / sorrow', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಆಶ್ಚರ್ಯ', 'āścarya', 'surprise / wonder', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಚಿಂತೆ', 'cinte', 'worry / anxiety', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನಗುಮುಖ', 'nagumukha', 'smiling face', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕನಸು', 'kanasu', 'dream', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನೆನಪು', 'nenapu', 'memory', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಯೋಚನೆ', 'yōcane', 'thought / thinking', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ನಿರ್ಧಾರ', 'nirdhāra', 'decision', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕಾರಣ', 'kāraṇa', 'reason / cause', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಪರಿಣಾಮ', 'pariṇāma', 'result / consequence', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬದಲಾವಣೆ', 'badalāvaṇe', 'change', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಅಭಿವೃದ್ಧಿ', 'abhivṛddhi', 'development / progress', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸಮಸ್ಯೆ', 'samasye', 'problem', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಪರಿಹಾರ', 'parihāra', 'solution', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಅವಕಾಶ', 'avakāśa', 'opportunity / chance', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಪ್ರಯತ್ನ', 'prayatna', 'effort / attempt', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಯಶಸ್ಸು', 'yaśassu', 'success', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸೋಲು', 'sōlu', 'defeat / failure', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಗುರಿ', 'guri', 'goal / aim / target', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಮಾರ್ಗ', 'mārga', 'path / way (formal)', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಆಸೆ', 'āse', 'desire / wish', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಅನುಭವ', 'anubhava', 'experience', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಪ್ರಮುಖ', 'pramukha', 'important / prominent', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸಾಮಾನ್ಯ', 'sāmānya', 'common / ordinary / general', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ವಿಶೇಷ', 'viśēṣa', 'special', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ವಿವಿಧ', 'vividha', 'various / diverse', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಉದಾಹರಣೆ', 'udāharaṇe', 'example', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಮಾಹಿತಿ', 'māhiti', 'information', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಸುದ್ದಿ', 'suddi', 'news', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಪತ್ರಿಕೆ', 'patrike', 'newspaper / magazine', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ದೂರದರ್ಶನ', 'dūradarśana', 'television', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ದನಿ', 'dani', 'voice / sound', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಶಬ್ದ', 'śabda', 'sound / word', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಬೆಳಕು', 'beḷaku', 'light', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಕತ್ತಲೆ', 'kattale', 'darkness', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಆಕಾರ', 'ākāra', 'shape / form', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಗಾತ್ರ', 'gātra', 'size', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಎತ್ತರ', 'ettara', 'height', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ತೂಕ', 'tūka', 'weight', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಉದ್ದ', 'udda', 'length', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಅಗಲ', 'agala', 'width', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ಆಳ', 'āḷa', 'depth', 3);
INSERT INTO words (kannada_word, transliteration, english_translation, level) VALUES ('ವ್ಯತ್ಯಾಸ', 'vyatyāsa', 'difference', 3);

-- Populate the 'sentences' table
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಮನೆ.', 'Idu mane.', 'This is a house.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾನು ಹಣ್ಣು ತಿನ್ನುತ್ತೇನೆ.', 'Nānu haṇṇu tinnuttēne.', 'I eat a fruit.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅದು ಮರ.', 'Adu mara.', 'That is a tree.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನೀನು ಬಾ.', 'Nīnu bā.', 'You come.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವನು ಹೋಗು.', 'Avanu hōgu.', 'He go.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವಳು ಓದು.', 'Avaḷu ōdu.', 'She read.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ನಾಯಿ.', 'Idu nāyi.', 'This is a dog.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅದು ಬೆಕ್ಕು.', 'Adu bekku.', 'That is a cat.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾನು ಹಾಲು ಕುಡಿ.', 'Nānu hālu kuḍi.', 'I drink milk.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನೀನು ನೀರು ಕೊಡು.', 'Nīnu nīru koḍu.', 'You give water.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಕೆಂಪು ಹೂವು.', 'Idu kempu hūvu.', 'This is a red flower.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅದು ಹಸಿರು ಗಿಡ.', 'Adu hasiru giḍa.', 'That is a green plant.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅಮ್ಮ ಊಟ ಮಾಡು.', 'Amma ūṭa māḍu.', 'Mother make food / eat.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅಪ್ಪ ಬಾ.', 'Appa bā.', 'Father come.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಪುಸ್ತಕ.', 'Idu pustaka.', 'This is a book.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾನು ಬರೆ.', 'Nānu bare.', 'I write.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನೀನು ನೋಡು.', 'Nīnu nōḍu.', 'You see.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವನು ನಗು.', 'Avanu nagu.', 'He laugh.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವಳು ಅಳು.', 'Avaḷu aḷu.', 'She cry.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಕಲ್ಲು.', 'Idu kallu.', 'This is a stone.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅದು ಮಣ್ಣು.', 'Adu maṇṇu.', 'That is soil.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾನು ನಡೆ.', 'Nānu naḍe.', 'I walk.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನೀನು ಓಡು.', 'Nīnu ōḍu.', 'You run.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅಕ್ಕ ಬಾ.', 'Akka bā.', 'Elder sister come.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ತಮ್ಮ ಹೋಗು.', 'Tamma hōgu.', 'Younger brother go.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಕೈ.', 'Idu kai.', 'This is a hand.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅದು ಕಾಲು.', 'Adu kālu.', 'That is a leg.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ತಲೆ.', 'Idu tale.', 'This is a head.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಮೂಗು.', 'Idu mūgu.', 'This is a nose.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಕಣ್ಣು.', 'Idu kaṇṇu.', 'This is an eye.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಕಿವಿ.', 'Idu kivi.', 'This is an ear.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಬಾಯಿ.', 'Idu bayi.', 'This is a mouth.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾನು ಒಂದು ಹಣ್ಣು ಕೊಡು.', 'Nānu ondu haṇṇu koḍu.', 'I give one fruit.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನೀನು ಎರಡು ಪುಸ್ತಕ ತೆಗೆದುಕೊ.', 'Nīnu eraḍu pustaka tegeduko.', 'You take two books.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅದು ದೊಡ್ಡ ಮನೆ.', 'Adu doḍḍa mane.', 'That is a big house.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಚಿಕ್ಕ ಮರ.', 'Idu cikka mara.', 'This is a small tree.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಹೊಸ ಬಟ್ಟೆ.', 'Idu hosa baṭṭe.', 'This is a new cloth.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅದು ಹಳೆ ಕಾರು.', 'Adu haḷe kāru.', 'That is an old car.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವನು ಒಳ್ಳೆ ಹುಡುಗ.', 'Avanu oḷḷe huḍuga.', 'He is a good boy.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವಳು ಒಳ್ಳೆ ಹುಡುಗಿ.', 'Avaḷu oḷḷe huḍugi.', 'She is a good girl.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಬಿಸಿ ನೀರು.', 'Idu bisi nīru.', 'This is hot water.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅದು ತಣ್ಣಗೆ ಇದೆ.', 'Adu taṇṇage ide.', 'That is cold.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಬಿಳಿ ಹಾಲು.', 'Idu biḷi hālu.', 'This is white milk.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅದು ಕಪ್ಪು ಬೆಕ್ಕು.', 'Adu kappu bekku.', 'That is a black cat.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಬಾನು ನೀಲಿ ಇದೆ.', 'Bānu nīli ide.', 'The sky is blue.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಹೂವು ಹಳದಿ ಇದೆ.', 'Hūvu haḷadi ide.', 'The flower is yellow.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾನು ಹಣ ಕೊಡು.', 'Nānu haṇa koḍu.', 'I give money.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನೀನು ಅಂಗಡಿಗೆ ಹೋಗು.', 'Nīnu angaḍige hōgu.', 'You go to the shop.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ದಾರ.', 'Idu dāra.', 'This is thread.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವಳು ಬಟ್ಟೆ ಕೊಡು.', 'Avaḷu baṭṭe koḍu.', 'She give clothes.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವನು ಕೈ ತೊಳಿ.', 'Avanu kai toḷi.', 'He wash hand.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಕಾಲು ನೋಡು.', 'Kālu nōḍu.', 'Look at the leg.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಏನು?', 'Idu ēnu?', 'What is this?', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅದು ಯಾರು?', 'Adu yāru?', 'Who is that?', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನೀನು ಎಲ್ಲಿ?', 'Nīnu elli?', 'Where are you?', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇಲ್ಲಿ ಬಾ.', 'Illi bā.', 'Come here.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅಲ್ಲಿ ಹೋಗು.', 'Alli hōgu.', 'Go there.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಹೌದು, ಇದು ಮನೆ.', 'Houdhu, idu mane.', 'Yes, this is a house.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇಲ್ಲ, ಅದು ಮರ.', 'Illa, adu mara.', 'No, that is a tree.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ನನ್ನ ಪುಸ್ತಕ.', 'Idu nanna pustaka.', 'This is my book.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅದು ನಿನ್ನ ಪೆನ್ನು.', 'Adu ninna pennu.', 'That is your pen.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವನ ಹೆಸರು ರಾಮ.', 'Avana hesaru Rāma.', 'His name is Rama.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವಳ ಹೆಸರು ಸೀತಾ.', 'Avaḷa hesaru Sītā.', 'Her name is Sita.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾಯಿ ಓಡು.', 'Nāyi ōḍu.', 'Dog run.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಬೆಕ್ಕು ಹಾಲು ಕುಡಿ.', 'Bekku hālu kuḍi.', 'Cat drink milk.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಮರ ದೊಡ್ಡದು ಇದೆ.', 'Mara doḍḍadu ide.', 'The tree is big.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಹೂವು ಚಿಕ್ಕದು ಇದೆ.', 'Hūvu cikkadu ide.', 'The flower is small.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ದಾರಿ.', 'Idu dāri.', 'This is the way.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅದು ರಸ್ತೆ.', 'Adu raste.', 'That is the road.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ನಗರ.', 'Idu nagara.', 'This is a city.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅದು ಹಳ್ಳಿ.', 'Adu haḷḷi.', 'That is a village.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾನು ಕೆಲಸ ಮಾಡು.', 'Nānu kelasa māḍu.', 'I do work.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನೀನು ಆಟ ಆಡು.', 'Nīnu āṭa āḍu.', 'You play game.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವಳು ಹಾಡು ಹಾಡು.', 'Avaḷu hāḍu hāḍu.', 'She sing song.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವನು ಮಾತು ಹೇಳು.', 'Avanu mātu hēḷu.', 'He speak word.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಬೆಂಕಿ.', 'Idu benki.', 'This is fire.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅದು ಹೊಗೆ.', 'Adu hoge.', 'That is smoke.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಗಾಳಿ ಬೀಸು.', 'Gāḷi bīsu.', 'Wind blow.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಬಣ್ಣ.', 'Idu baṇṇa.', 'This is color.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಐದು.', 'Idu aidu.', 'This is five.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅದು ನಾಲ್ಕು.', 'Adu nālku.', 'That is four.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಮೂರು.', 'Idu mūru.', 'This is three.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾನು ಕೇಳು.', 'Nānu kēḷu.', 'I listen/ask.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನೀನು ಹೇಳು.', 'Nīnu hēḷu.', 'You tell.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಕುಳಿತುಕೊ.', 'Kuḷituko.', 'Sit down.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಿಲ್ಲು.', 'Nillu.', 'Stop/Stand.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಕಾಗದ.', 'Idu kāgada.', 'This is paper.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಮೇಜು.', 'Idu mēju.', 'This is a table.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅದು ಕುರ್ಚಿ.', 'Adu kurci.', 'That is a chair.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಹಾಸಿಗೆ.', 'Idu hāsige.', 'This is a bed.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಬಾಗಿಲು ತೆರೆ.', 'Bāgilu tere.', 'Open the door.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಕಿಟಕಿ ಮುಚ್ಚು.', 'Kiṭaki muccu.', 'Close the window.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ದಿನ.', 'Idu dina.', 'This is day.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅದು ರಾತ್ರಿ.', 'Adu rātri.', 'That is night.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ತಂಗಿ ಬಾ.', 'Tangi bā.', 'Younger sister come.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅಣ್ಣ ಹೋಗು.', 'Aṇṇa hōgu.', 'Elder brother go.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಗೆಳೆಯ ಯಾರು?', 'Geḷeya yāru?', 'Who is the friend (male)?', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಗೆಳತಿ ಎಲ್ಲಿ?', 'Geḷati elli?', 'Where is the friend (female)?', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಪಥ.', 'Idu patha.', 'This is a path.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾನು ಶಾಲೆಗೆ ಹೋಗು.', 'Nānu śālege hōgu.', 'I go to school.', 1);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾನು ನೀರು ಕುಡಿಯುತ್ತೇನೆ.', 'Nānu nīru kuḍiyuttēne.', 'I drink water.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಪುಸ್ತಕ ಟೇಬಲ್ ಮೇಲೆ ಇದೆ.', 'Pustaka ṭēbal mēle ide.', 'The book is on the table.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವನು ನಿಧಾನವಾಗಿ ನಡೆಯುತ್ತಾನೆ.', 'Avanu nidhānavāgi naḍeyuttāne.', 'He walks slowly.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವಳು ಬೇಗ ಓಡುತ್ತಾಳೆ.', 'Avaḷu bēga ōḍuttāḷe.', 'She runs quickly.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಸೂರ್ಯ ಪೂರ್ವದಲ್ಲಿ ಉದಯಿಸುತ್ತಾನೆ.', 'Sūrya pūrvadalli udayisuttāne.', 'The sun rises in the east.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಚಂದ್ರ ರಾತ್ರಿ ಕಾಣಿಸುತ್ತಾನೆ.', 'Candra rātri kāṇisuttāne.', 'The moon appears at night.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಆಕಾಶದಲ್ಲಿ ನಕ್ಷತ್ರಗಳು ಇವೆ.', 'Ākāśadalli nakṣatragaḷu ive.', 'There are stars in the sky.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇಂದು ಮಳೆ ಬರಬಹುದು.', 'Indu maḷe barabahudu.', 'It might rain today.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಮೋಡಗಳು ಕಪ್ಪಾಗಿವೆ.', 'Mōḍagaḷu kappāgive.', 'The clouds are black.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನದಿ ಹರಿಯುತ್ತಿದೆ.', 'Nadi hariyuttide.', 'The river is flowing.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಬೆಟ್ಟ ಎತ್ತರವಾಗಿದೆ.', 'Beṭṭa ettaravāgide.', 'The hill is high.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಕಾಡಿನಲ್ಲಿ ಪ್ರಾಣಿಗಳಿವೆ.', 'Kāḍinalli prāṇigaḷive.', 'There are animals in the forest.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಈಗ ಸಮಯ ಎಷ್ಟು?', 'Īga samaya eṣṭu?', 'What time is it now?', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾಳೆ ವಾರ.', 'Nāḷe vāra.', 'Tomorrow is the weekly market.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಿನ್ನೆ ನಾನು ಶಾಲೆಗೆ ಹೋಗಿದ್ದೆ.', 'Ninne nānu śālege hōgidde.', 'Yesterday I had gone to school.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಈ ತಿಂಗಳು ತುಂಬಾ ಬಿಸಿಲಿದೆ.', 'Ī tingaḷu tumbā bisilide.', 'This month is very sunny/hot.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಕಳೆದ ವರ್ಷ ನಾನು ಇಲ್ಲಿ ಇರಲಿಲ್ಲ.', 'Kaḷeda varṣa nānu illi iralilla.', 'Last year I was not here.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಬೆಳಿಗ್ಗೆ ಬೇಗ ಏಳು.', 'Beḷigge bēga ēḷu.', 'Wake up early in the morning.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಸಂಜೆ ಆಟ ಆಡೋಣ.', 'Sanje āṭa āḍōṇa.', 'Let''s play in the evening.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ದೇವರು ಎಲ್ಲರನ್ನು ರಕ್ಷಿಸಲಿ.', 'Dēvaru ellarannu rakṣisali.', 'May God protect everyone.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಗುಡಿಯಲ್ಲಿ ಪೂಜೆ ನಡೆಯುತ್ತಿದೆ.', 'Guḍiyalli pūje naḍeyuttide.', 'Worship is happening in the temple.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನನ್ನ ಪ್ರಶ್ನೆಗೆ ಉತ್ತರ ಕೊಡು.', 'Nanna praśnege uttara koḍu.', 'Give the answer to my question.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವನಿಗೆ ಉತ್ತರ ಗೊತ್ತಿಲ್ಲ.', 'Avanige uttara gottilla.', 'He doesn''t know the answer.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಪ್ರೀತಿ ಜೀವನದ ಭಾಗ.', 'Prīti jīvanada bhāga.', 'Love is a part of life.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಯಾರನ್ನೂ ದ್ವೇಷಿಸಬೇಡ.', 'Yārannū dvēṣisabēḍa.', 'Don''t hate anyone.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಕೋಪ ಒಳ್ಳೆಯದಲ್ಲ.', 'Kōpa oḷḷeyadalla.', 'Anger is not good.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಶಾಂತಿಯಿಂದ ಇರಿ.', 'Śāntiyinda iri.', 'Be peaceful.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಧೈರ್ಯವಾಗಿ ಮುಂದೆ ಸಾಗು.', 'Dhairyavāgi munde sāgu.', 'Move forward courageously.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಿನಗೆ ಭಯ ಏಕೆ?', 'Ninage bhaya ēke?', 'Why are you afraid?', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಈ ಹೂವು ಸುಂದರವಾಗಿದೆ.', 'Ī hūvu sundaravāgide.', 'This flower is beautiful.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವಳ ಮುಖ ನೋಡಿದೆ.', 'Avaḷa mukha nōḍide.', 'I saw her face.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ದೇಹ ಆರೋಗ್ಯವಾಗಿರಲಿ.', 'Dēha ārōgyavāgirali.', 'May the body be healthy.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವನಿಗೆ ಬಹಳ ಶಕ್ತಿ ಇದೆ.', 'Avanige bahaḷa śakti ide.', 'He has a lot of strength.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಜ್ಞಾನ ಶಕ್ತಿ ಇದ್ದಂತೆ.', 'Jñāna śakti iddante.', 'Knowledge is like power.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಕನ್ನಡ ಒಂದು ಸುಂದರ ಭಾಷೆ.', 'Kannaḍa ondu sundara bhāṣe.', 'Kannada is a beautiful language.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಮ್ಮ ದೇಶ ಭಾರತ.', 'Namma dēśa Bhārata.', 'Our country is India.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಕರ್ನಾಟಕ ಒಂದು ರಾಜ್ಯ.', 'Karnāṭaka ondu rājya.', 'Karnataka is a state.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಜನ ಸಂತೋಷವಾಗಿದ್ದಾರೆ.', 'Jana santoṣavāgiddāre.', 'The people are happy.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವಳು ಅವನ ಹೆಂಡತಿ.', 'Avaḷu avana henḍati.', 'She is his wife.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವನು ಅವಳ ಗಂಡ.', 'Avanu avaḷa gaṇḍa.', 'He is her husband.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಮಗು ನಗುತ್ತಿದೆ.', 'Magu naguttide.', 'The child is laughing.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಆ ಹುಡುಗ ಯಾರು?', 'Ā huḍuga yāru?', 'Who is that boy?', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಈ ಹುಡುಗಿ ಚೆನ್ನಾಗಿ ಓದುತ್ತಾಳೆ.', 'Ī huḍugi cennāgi ōduttāḷe.', 'This girl studies well.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವನು ನನ್ನ ಸ್ನೇಹಿತ.', 'Avanu nanna snēhita.', 'He is my friend.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವಳು ನನ್ನ ಸ್ನೇಹಿತೆ.', 'Avaḷu nanna snēhite.', 'She is my friend.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಶಿಕ್ಷಕ ಪಾಠ ಹೇಳುತ್ತಿದ್ದಾರೆ.', 'Śikṣaka pāṭha hēḷuttiddāre.', 'The teacher is teaching a lesson.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಶಿಕ್ಷಕಿ ಪ್ರಶ್ನೆ ಕೇಳಿದರು.', 'Śikṣaki praśne kēḷidaru.', 'The teacher (female) asked a question.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ವಿದ್ಯಾರ್ಥಿ ಗಮನವಿಟ್ಟು ಕೇಳುತ್ತಿದ್ದಾನೆ.', 'Vidyārthi gamanaviṭṭu kēḷuttiddāne.', 'The student is listening attentively.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ವೈದ್ಯರು ಆಸ್ಪತ್ರೆಯಲ್ಲಿದ್ದಾರೆ.', 'Vaidyaru āspatreyalliddāre.', 'The doctor is in the hospital.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಆಹಾರ ರುಚಿಕರವಾಗಿದೆ.', 'Āhāra rucikaravāgide.', 'The food is tasty.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ತರಕಾರಿ ಆರೋಗ್ಯಕ್ಕೆ ಒಳ್ಳೆಯದು.', 'Tarakāri ārōgyakke oḷḷeyadu.', 'Vegetables are good for health.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅಕ್ಕಿ ಅಂಗಡಿಯಲ್ಲಿ ಸಿಗುತ್ತದೆ.', 'Akki angaḍiyalli siguttade.', 'Rice (uncooked) is available in the shop.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅನ್ನ ಬಿಸಿಯಾಗಿದೆ.', 'Anna bisiyāgide.', 'The rice (cooked) is hot.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಈ ಹಣ್ಣು ಸಿಹಿಯಾಗಿದೆ.', 'Ī haṇṇu sihiyāgide.', 'This fruit is sweet.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಿಂಬೆ ಹಣ್ಣು ಹುಳಿಯಾಗಿದೆ.', 'Nimbe haṇṇu huḷiyāgide.', 'The lemon is sour.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಊಟ ತುಂಬಾ ಖಾರವಾಗಿತ್ತು.', 'Ūṭa tumbā khāravāgittu.', 'The meal was very spicy.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನನಗೆ ಸ್ವಲ್ಪ ಉಪ್ಪು ಕೊಡು.', 'Nanage svalpa uppu koḍu.', 'Give me a little salt.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಈ ಸೊಪ್ಪು ಕಹಿಯಾಗಿದೆ.', 'Ī soppu kahiyāgide.', 'These greens are bitter.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನನಗೆ ಹಸಿವಾಗಿದೆ.', 'Nanage hasivāgide.', 'I am hungry.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವನಿಗೆ ಬಾಯಾರಿಕೆಯಾಗಿದೆ.', 'Avanige bāyārikeyāgide.', 'He is thirsty.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ರಾತ್ರಿ ಬೇಗ ನಿದ್ರೆ ಮಾಡು.', 'Rātri bēga nidre māḍu.', 'Sleep early at night.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇಲ್ಲಿ ಹತ್ತಿರ ಬಾ.', 'Illi hattira bā.', 'Come near here.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅಲ್ಲಿ ದೂರ ಹೋಗು.', 'Alli dūra hōgu.', 'Go far there.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಮನೆಯ ಒಳಗೆ ಬಾ.', 'Maneya oḷage bā.', 'Come inside the house.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಮನೆಯ ಹೊರಗೆ ಹೋಗು.', 'Maneya horage hōgu.', 'Go outside the house.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಕಾರು ಮನೆಯ ಮುಂದೆ ಇದೆ.', 'Kāru maneya munde ide.', 'The car is in front of the house.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಮರ ಮನೆಯ ಹಿಂದೆ ಇದೆ.', 'Mara maneya hinde ide.', 'The tree is behind the house.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವನು ನನ್ನ ಪಕ್ಕ ಕುಳಿತಿದ್ದಾನೆ.', 'Avanu nanna pakka kuḷitiddāne.', 'He is sitting beside me.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ರಸ್ತೆಯ ಮಧ್ಯ ನಡೆಯಬೇಡ.', 'Rasteya madhya naḍeyabēḍa.', 'Don''t walk in the middle of the road.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಮನೆಯ ಸುತ್ತ ಗಿಡಗಳಿವೆ.', 'Maneya sutta giḍagaḷive.', 'There are plants around the house.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನೇರವಾಗಿ ಹೋಗು.', 'Nēravāgi hōgu.', 'Go straight.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಬಲಕ್ಕೆ ತಿರುಗು.', 'Balakke tirugu.', 'Turn right.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಎಡಕ್ಕೆ ನೋಡು.', 'Eḍakke nōḍu.', 'Look left.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವಳಿಗೆ ತುಂಬಾ ಕೆಲಸ ಇದೆ.', 'Avaḷige tumbā kelasa ide.', 'She has a lot of work.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನನಗೆ ಸ್ವಲ್ಪ ನೀರು ಬೇಕು.', 'Nanage svalpa nīru bēku.', 'I need a little water.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇನ್ನೂ ಹೆಚ್ಚು ಅನ್ನ ಹಾಕು.', 'Innū heccu anna hāku.', 'Serve more rice.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಶಬ್ದ ಕಡಿಮೆ ಮಾಡು.', 'Śabda kaḍime māḍu.', 'Reduce the noise.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಈ ಕೆಲಸ ಸುಲಭವಾಗಿದೆ.', 'Ī kelasa sulabhavāgide.', 'This work is easy.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಆ ಪರೀಕ್ಷೆ ಕಷ್ಟವಾಗಿತ್ತು.', 'Ā parīkṣe kaṣṭavāgittu.', 'That exam was difficult.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನೀರು ಶುದ್ಧವಾಗಿದೆ.', 'Nīru śuddhavāgide.', 'The water is pure.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಆನೆ ದೊಡ್ಡ ಪ್ರಾಣಿ.', 'Āne doḍḍa prāṇi.', 'Elephant is a big animal.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಗಿಳಿ ಹಸಿರು ಪಕ್ಷಿ.', 'Giḷi hasiru pakṣi.', 'Parrot is a green bird.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಮೀನು ನೀರಿನಲ್ಲಿ ವಾಸಿಸುತ್ತದೆ.', 'Mīnu nīrinalli vāsisuttade.', 'Fish lives in water.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಹಾವು ಹುತ್ತದಲ್ಲಿದೆ.', 'Hāvu huttadallide.', 'The snake is in the anthill.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಕುದುರೆ ವೇಗವಾಗಿ ಓಡುತ್ತದೆ.', 'Kudure vēgavāgi ōḍuttade.', 'The horse runs fast.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಹಸು ಹಾಲು ಕೊಡುತ್ತದೆ.', 'Hasu hālu koḍuttade.', 'The cow gives milk.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇರುವೆ ಸಾಲಿನಲ್ಲಿ ಹೋಗುತ್ತಿದೆ.', 'Iruve sālinalli hōguttide.', 'The ant is going in a line.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾನು ಹೇಗೆ ಬರಲಿ?', 'Nānu hēge barali?', 'How should I come?', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನೀನು ಯಾಕೆ ಅಳುತ್ತಿರುವೆ?', 'Nīnu yāke aḷuttiruve?', 'Why are you crying?', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವರು ಯಾವಾಗ ಬರುತ್ತಾರೆ?', 'Avaru yāvāga baruttāre?', 'When will they come?', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಈ ಪುಸ್ತಕದ ಬೆಲೆ ಎಷ್ಟು?', 'Ī pustakada bele eṣṭu?', 'How much is the price of this book?', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅದು ದೊಡ್ಡದು, ಇದು ಚಿಕ್ಕದು.', 'Adu doḍḍadu, idu cikkadu.', 'That is big, this is small.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಪೆನ್ ಮೇಜಿನ ಕೆಳಗೆ ಬಿದ್ದಿದೆ.', 'Pen mējina keḷage biddide.', 'The pen has fallen under the table.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಗಂಟೆ ಶಬ್ದ ಕೇಳಿಸಿತು.', 'Ganṭe śabda kēḷisitu.', 'The sound of the bell was heard.', 2);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಶಿಕ್ಷಣ ಬಹುಮುಖ್ಯವಾಗಿದೆ.', 'Śikṣaṇa bahumukhyavāgide.', 'Education is very important.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾನು ವಿದ್ಯಾಲಯಕ್ಕೆ ಹೋಗುತ್ತೇನೆ.', 'Nānu vidyālayakke hōguttēne.', 'I go to school.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ವಿಮಾನ ವೇಗವಾಗಿ ಚಲಿಸುತ್ತದೆ.', 'Vimāna vēgavāgi calisuttade.', 'The airplane moves fast.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ರೈಲು ನಿಲ್ದಾಣಕ್ಕೆ ಬಂದಿತು.', 'Railu nildāṇakke banditu.', 'The train arrived at the station.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಹಡಗು ಸಮುದ್ರದಲ್ಲಿ ಪ್ರಯಾಣಿಸುತ್ತದೆ.', 'Haḍagu samudradalli prayāṇisuttade.', 'The ship travels on the sea.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಸಮುದ್ರ ತೀರದಲ್ಲಿ ಅಲೆಗಳಿವೆ.', 'Samudra tīradalli alegaḷive.', 'There are waves on the seashore.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನನ್ನ ಪ್ರಯಾಣ ಸುಖಕರವಾಗಿತ್ತು.', 'Nanna prayāṇa sukhakaravāgittu.', 'My journey was comfortable.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಗ್ರಾಮ ಜೀವನ ಶಾಂತವಾಗಿರುತ್ತದೆ.', 'Grāma jīvana śāntavāgiruttade.', 'Village life is peaceful.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಕ್ಷೆ ದಾರಿ ತೋರಿಸುತ್ತದೆ.', 'Nakṣe dāri tōrisuttade.', 'The map shows the way.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಸರ್ಕಾರ ಜನರಿಗಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ.', 'Sarkāra janarigāgi kelasa māḍuttade.', 'The government works for the people.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಕಾನೂನು ಎಲ್ಲರಿಗೂ ಸಮಾನ.', 'Kānūnu ellarigū samāna.', 'The law is equal for everyone.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನ್ಯಾಯ ಎಲ್ಲರಿಗೂ ಸಿಗಬೇಕು.', 'Nyāya ellarigū sigabēku.', 'Justice should be available to everyone.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅಪರಾಧ ಮಾಡುವುದು ತಪ್ಪು.', 'Aparādha māḍuvudu tappu.', 'Committing a crime is wrong.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ತಪ್ಪು ಮಾಡಿದರೆ ಶಿಕ್ಷೆ ಆಗುತ್ತದೆ.', 'Tappu māḍidare śikṣe āguttade.', 'If you do wrong, you will be punished.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಭಾರತಕ್ಕೆ ೧೯೪೭ ರಲ್ಲಿ ಸ್ವಾತಂತ್ರ್ಯ ಸಿಕ್ಕಿತು.', 'Bhāratakke 1947 ralli svātantrya sikkitu.', 'India got independence in 1947.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಸ್ವಾತಂತ್ರ್ಯಕ್ಕಾಗಿ ಅನೇಕರು ಹೋರಾಟ ಮಾಡಿದರು.', 'Svātantryakkāgi anēkaru hōrāṭa māḍidaru.', 'Many people struggled for freedom.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾವು ಸಮಾಜದಲ್ಲಿ ಒಟ್ಟಿಗೆ ಬಾಳುತ್ತೇವೆ.', 'Nāvu samājadalli oṭṭige bāḷuttēve.', 'We live together in society.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಭಾರತೀಯ ಸಂಸ್ಕೃತಿ ವೈವಿಧ್ಯಮಯವಾಗಿದೆ.', 'Bhāratīya saṁskṛti vaividhyamayavāgide.', 'Indian culture is diverse.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಹಬ್ಬಗಳು ನಮ್ಮ ಪರಂಪರೆಯ ಭಾಗ.', 'Habbagaḷu namma parampareya bhāga.', 'Festivals are part of our tradition.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಧರ್ಮ ಸನ್ಮಾರ್ಗವನ್ನು ತೋರಿಸುತ್ತದೆ.', 'Dharma sanmārgavannu tōrisuttade.', 'Religion shows the right path.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನನಗೆ ನಿನ್ನ ಮೇಲೆ ನಂಬಿಕೆ ಇದೆ.', 'Nanage ninna mēle nambike ide.', 'I have trust in you.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ವಿಜ್ಞಾನ ಪ್ರಗತಿಗೆ ಕಾರಣವಾಗಿದೆ.', 'Vijñāna pragatige kāraṇavāgide.', 'Science is the reason for progress.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ತಂತ್ರಜ್ಞಾನ ನಮ್ಮ ಜೀವನವನ್ನು ಸುಲಭಗೊಳಿಸಿದೆ.', 'Tantrajñāna namma jīvanavannu sulabhagoḷiside.', 'Technology has made our lives easier.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾವು ಪರಿಸರವನ್ನು ರಕ್ಷಿಸಬೇಕು.', 'Nāvu parisaravannu rakṣisabēku.', 'We must protect the environment.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಭವಿಷ್ಯದ ಬಗ್ಗೆ ಯೋಚಿಸು.', 'Bhaviṣyada bagge yōcisu.', 'Think about the future.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಭೂತಕಾಲವನ್ನು ಮರೆಯಬಾರದು.', 'Bhūtakālavannu mareyabāradu.', 'One should not forget the past.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ವರ್ತಮಾನದಲ್ಲಿ ಜೀವಿಸು.', 'Vartamānadalli jīvisu.', 'Live in the present.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಕಲೆ ಮನಸ್ಸಿಗೆ ಆನಂದ ನೀಡುತ್ತದೆ.', 'Kale manassige ānanda nīḍuttade.', 'Art gives joy to the mind.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಸಂಗೀತ ಕೇಳಲು ನನಗೆ ಇಷ್ಟ.', 'Sangīta kēḷalu nanage iṣṭa.', 'I like to listen to music.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವಳು ಚೆನ್ನಾಗಿ ನೃತ್ಯ ಮಾಡುತ್ತಾಳೆ.', 'Avaḷu cennāgi nṛtya māḍuttāḷe.', 'She dances well.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾವು ನಿನ್ನೆ ನಾಟಕ ನೋಡಿದೆವು.', 'Nāvu ninne nāṭaka nōḍidevu.', 'We watched a play yesterday.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಈ ಚಿತ್ರ ಬಹಳ ಸುಂದರವಾಗಿದೆ.', 'Ī citra bahaḷa sundaravāgide.', 'This picture is very beautiful.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಕನ್ನಡ ಸಾಹಿತ್ಯ ಶ್ರೀಮಂತವಾಗಿದೆ.', 'Kannaḍa sāhitya śrīmantavāgide.', 'Kannada literature is rich.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವರು ಒಂದು ಕವಿತೆ ಬರೆದರು.', 'Avaru ondu kavite baredaru.', 'He/She wrote a poem.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅಜ್ಜಿ ನಮಗೆ ಕಥೆ ಹೇಳಿದರು.', 'Ajji namage kathe hēḷidaru.', 'Grandmother told us a story.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಈ ಲೇಖನ ಉಪಯುಕ್ತವಾಗಿದೆ.', 'Ī lēkhana upayuktavāgide.', 'This article is useful.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವನು ವ್ಯಾಪಾರ ಮಾಡುತ್ತಾನೆ.', 'Avanu vyāpāra māḍuttāne.', 'He does business.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವಳಿಗೆ ಒಳ್ಳೆಯ ಉದ್ಯೋಗ ಸಿಕ್ಕಿದೆ.', 'Avaḷige oḷḷeya udyōga sikkide.', 'She has got a good job.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಕೃಷಿ ಭಾರತದ ಆರ್ಥಿಕತೆಗೆ ಮುಖ್ಯ.', 'Kṛṣi bhāratada ārthikatege mukhya.', 'Agriculture is important to India''s economy.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ರೈತ ಹೊಲದಲ್ಲಿ ಕೆಲಸ ಮಾಡುತ್ತಾನೆ.', 'Raita holadalli kelasa māḍuttāne.', 'The farmer works in the field.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಭೂಮಿ ಫಲವತ್ತಾಗಿದೆ.', 'Bhūmi phalavattāgide.', 'The land is fertile.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಈ ವರ್ಷ ಬೆಳೆ ಚೆನ್ನಾಗಿ ಬಂದಿದೆ.', 'Ī varṣa beḷe cennāgi bandide.', 'The crop has come well this year.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಗಿಡಗಳಿಗೆ ಪ್ರತಿದಿನ ನೀರುಹಾಕು.', 'Giḍagaḷige pratidina nīruhāku.', 'Water the plants daily.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅಮ್ಮ ಅಡುಗೆ ಮಾಡುತ್ತಿದ್ದಾರೆ.', 'Amma aḍuge māḍuttiddāre.', 'Mother is cooking.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಪಾತ್ರೆಯನ್ನು ಸ್ವಚ್ಛವಾಗಿ ತೊಳೆ.', 'Pātreyannu svacchavāgi toḷe.', 'Wash the vessel cleanly.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಚಮಚದಿಂದ ತಿನ್ನು.', 'Camacadinda tinnu.', 'Eat with a spoon.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ತಟ್ಟೆಯಲ್ಲಿ ಊಟ ಬಡಿಸು.', 'Taṭṭeyalli ūṭa baḍisu.', 'Serve the meal on the plate.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಲೋಟದಲ್ಲಿ ನೀರು ತುಂಬಿಸು.', 'Lōṭadalli nīru tumbisu.', 'Fill water in the glass.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಿಜವಾದ ಸ್ನೇಹ ಅಮೂಲ್ಯ.', 'Nijavāda snēha amūlya.', 'True friendship is precious.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವರ ಸಂಬಂಧ ಗಟ್ಟಿಯಾಗಿದೆ.', 'Avara sambandha gaṭṭiyāgide.', 'Their relationship is strong.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನನ್ನ ಕುಟುಂಬ ದೊಡ್ಡದು.', 'Nanna kuṭumba doḍḍadu.', 'My family is large.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನೆರೆಹೊರೆಯವರೊಂದಿಗೆ ಚೆನ್ನಾಗಿರು.', 'Nerehoreyavarondige cennāgiru.', 'Be good with neighbors.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವನು ನನಗೆ ಸಹಾಯ ಮಾಡಿದನು.', 'Avanu nanage sahāya māḍidanu.', 'He helped me.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾನು ನಿನಗೆ ಉಡುಗೊರೆ ತಂದಿದ್ದೇನೆ.', 'Nānu ninage uḍugore tandiddēne.', 'I have brought a gift for you.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾವು ದೀಪಾವಳಿ ಹಬ್ಬ ಆಚರಿಸುತ್ತೇವೆ.', 'Nāvu dīpāvaḷi habba ācarisuttēve.', 'We celebrate the Diwali festival.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಆಚರಣೆ ಸಂಭ್ರಮದಿಂದ ಕೂಡಿತ್ತು.', 'Ācaraṇe sambhramadinda kūḍittu.', 'The celebration was full of joy.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಶಾಲೆಯಲ್ಲಿ ವಾರ್ಷಿಕ ಕಾರ್ಯಕ್ರಮವಿದೆ.', 'Śāleyalli vārṣika kāryakramavide.', 'There is an annual program at the school.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಮದುವೆಗೆ ಆಹ್ವಾನ ಬಂದಿದೆ.', 'Maduvēge āhvāna bandide.', 'An invitation for the wedding has come.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾವು ಪ್ರತಿದಿನ ಪ್ರಾರ್ಥನೆ ಮಾಡುತ್ತೇವೆ.', 'Nāvu pratidina prārthane māḍuttēve.', 'We pray every day.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಹಿರಿಯರ ಆಶೀರ್ವಾದ ಪಡೆಯಬೇಕು.', 'Hiriyara āśīrvāda paḍeyabēku.', 'One should get blessings from elders.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವನು ತುಂಬಾ ಸಂತೋಷವಾಗಿದ್ದನು.', 'Avanu tumbā santoṣavāgiddanu.', 'He was very happy.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ದುಃಖ ಪಡಬೇಡ, ಎಲ್ಲವೂ ಸರಿಹೋಗುತ್ತದೆ.', 'Duḥkha paḍabēḍa, ellavū sarihōguttade.', 'Don''t be sad, everything will be alright.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವನಿಗೆ ಆಶ್ಚರ್ಯವಾಯಿತು.', 'Avanige āścaryavāyitu.', 'He was surprised.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಯಾವುದಕ್ಕೂ ಚಿಂತೆ ಮಾಡಬೇಡ.', 'Yāvudakkū cinte māḍabēḍa.', 'Don''t worry about anything.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವಳ ನಗುಮುಖ ಎಲ್ಲರಿಗೂ ಇಷ್ಟ.', 'Avaḷa nagumukha ellarigū iṣṭa.', 'Everyone likes her smiling face.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾನು ನಿನ್ನೆ ಒಂದು ಕನಸು ಕಂಡೆ.', 'Nānu ninne ondu kanasu kaṇḍe.', 'I saw a dream yesterday.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಹಳೆಯ ನೆನಪುಗಳು ಮರುಕಳಿಸಿದವು.', 'Haḷeya nenapugaḷu marukaḷisidavu.', 'Old memories recurred.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಒಳ್ಳೆಯ ಯೋಚನೆಗಳನ್ನು ಮಾಡು.', 'Oḷḷeya yōcanegaḷannu māḍu.', 'Think good thoughts.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾವು ಸರಿಯಾದ ನಿರ್ಧಾರ ತೆಗೆದುಕೊಳ್ಳಬೇಕು.', 'Nāvu sariyāda nirdhāra tegedukoḷḷabēku.', 'We must take the right decision.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದಕ್ಕೆ ಕಾರಣ ಏನು?', 'Idakke kāraṇa ēnu?', 'What is the reason for this?', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಪ್ರತಿ ಕ್ರಿಯೆಗೆ ಒಂದು ಪರಿಣಾಮ ಇರುತ್ತದೆ.', 'Prati kriyege ondu pariṇāma iruttade.', 'Every action has a result.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಜಗತ್ತಿನಲ್ಲಿ ಬದಲಾವಣೆ ನಿರಂತರ.', 'Jagattinalli badalāvaṇe nirantara.', 'Change is constant in the world.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ದೇಶದ ಅಭಿವೃದ್ಧಿ ಮುಖ್ಯ.', 'Dēśada abhivṛddhi mukhya.', 'The country''s development is important.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಪ್ರತಿಯೊಂದು ಸಮಸ್ಯೆಗೆ ಪರಿಹಾರವಿದೆ.', 'Pratiyondu samasyege parihāravide.', 'There is a solution to every problem.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಮಗೆ ಒಳ್ಳೆಯ ಅವಕಾಶ ಸಿಕ್ಕಿದೆ.', 'Namage oḷḷeya avakāśa sikkide.', 'We have got a good opportunity.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಪ್ರಯತ್ನ ಪಟ್ಟರೆ ಯಶಸ್ಸು ಖಂಡಿತ.', 'Prayatna paṭṭare yaśassu khaṇḍita.', 'If you make an effort, success is definite.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಸೋಲನ್ನು ಒಪ್ಪಿಕೊಳ್ಳಲು ಕಲಿ.', 'Sōlannu oppikoḷḷalu kali.', 'Learn to accept defeat.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನನ್ನ ಗುರಿ ವೈದ್ಯನಾಗುವುದು.', 'Nanna guri vaidyanāguvudu.', 'My goal is to become a doctor.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಸರಿಯಾದ ಮಾರ್ಗವನ್ನು ಅನುಸರಿಸು.', 'Sariyāda mārgavannu anusarisu.', 'Follow the right path.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವಳಿಗೆ ವಿದೇಶಕ್ಕೆ ಹೋಗುವ ಆಸೆ.', 'Avaḷige vidēśakke hōguva āse.', 'She desires to go abroad.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಪ್ರಯಾಣದಿಂದ ಹೊಸ ಅನುಭವ ಸಿಗುತ್ತದೆ.', 'Prayāṇadinda hosa anubhava siguttade.', 'One gets new experiences from traveling.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಪ್ರಮುಖ ವಿಷಯ.', 'Idu pramukha viṣaya.', 'This is an important matter.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇದು ಸಾಮಾನ್ಯ ಸಂಗತಿ.', 'Idu sāmānya sangati.', 'This is a common thing.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇಂದು ವಿಶೇಷ ದಿನ.', 'Indu viśēṣa dina.', 'Today is a special day.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇಲ್ಲಿ ವಿವಿಧ ರೀತಿಯ ಹಣ್ಣುಗಳಿವೆ.', 'Illi vividha rītiya haṇṇugaḷive.', 'There are various types of fruits here.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಒಂದು ಉದಾಹರಣೆ ಕೊಡು.', 'Ondu udāharaṇe koḍu.', 'Give an example.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ದಯವಿಟ್ಟು ನನಗೆ ಮಾಹಿತಿ ನೀಡಿ.', 'Dayaviṭṭu nanage māhiti nīḍi.', 'Please give me information.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಇಂದಿನ ಮುಖ್ಯ ಸುದ್ದಿ ಏನು?', 'Indina mukhya suddi ēnu?', 'What is today''s main news?', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನಾನು ಪ್ರತಿದಿನ ಪತ್ರಿಕೆ ಓದುತ್ತೇನೆ.', 'Nānu pratidina patrike ōduttēne.', 'I read the newspaper every day.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ದೂರದರ್ಶನದಲ್ಲಿ ಚಲನಚಿತ್ರ ನೋಡಿದೆ.', 'Dūradarśanadalli calanacitra nōḍide.', 'I watched a movie on television.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಅವಳ ದನಿ ಮಧುರವಾಗಿದೆ.', 'Avaḷa dani madhuravāgide.', 'Her voice is sweet.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಹೊರಗಿನಿಂದ ಶಬ್ದ ಬರುತ್ತಿದೆ.', 'Horagininda śabda baruttide.', 'Noise is coming from outside.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಕೋಣೆಯಲ್ಲಿ ಬೆಳಕು ಕಡಿಮೆಯಿದೆ.', 'Kōṇeyalli beḷaku kaḍimeyide.', 'The light in the room is low.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಕತ್ತಲೆಯಲ್ಲಿ ನಡೆಯುವುದು ಕಷ್ಟ.', 'Kattaleyalli naḍeyuvudu kaṣṭa.', 'It is difficult to walk in the dark.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಚಂದ್ರನ ಆಕಾರ ಬದಲಾಗುತ್ತದೆ.', 'Candrana ākāra badalāguttade.', 'The shape of the moon changes.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಈ ಪೆಟ್ಟಿಗೆಯ ಗಾತ್ರ ದೊಡ್ಡದಿದೆ.', 'Ī peṭṭigeya gātra doḍḍadide.', 'The size of this box is big.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಆ ಮರ ತುಂಬಾ ಎತ್ತರವಿದೆ.', 'Ā mara tumbā ettaravide.', 'That tree is very tall.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ನನ್ನ ತೂಕ ೬೦ ಕೆಜಿ ಇದೆ.', 'Nanna tūka 60 keji ide.', 'My weight is 60 kg.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಈ ಹಗ್ಗದ ಉದ್ದ ಎಷ್ಟು?', 'Ī haggada udda eṣṭu?', 'What is the length of this rope?', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ರಸ್ತೆಯ ಅಗಲ ಸಾಕಷ್ಟಿದೆ.', 'Rasteya agala sākṣṭide.', 'The width of the road is sufficient.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಬಾವಿಯ ಆಳ ಹೆಚ್ಚಿದೆ.', 'Bāviya āḷa heccide.', 'The depth of the well is more.', 3);
INSERT INTO sentences (kannada_sentence, transliteration, english_translation, level) VALUES ('ಈ ಎರಡರ ನಡುವೆ ವ್ಯತ್ಯಾಸವಿದೆ.', 'Ī eraḍara naḍuve vyatyāsavide.', 'There is a difference between these two.', 3);
